title: NutriComposer
description: A comprehensive nutrition tracking iOS app that helps you compose your daily nutrient intake
baseurl: "/nutricomposer-support"
url: "https://naveedulislam.github.io"
remote_theme: jekyll/minima

minima:
  skin: dark

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

header_pages:
  - features.md
  - support.md
  - privacy-policy.md
  - faq.md
  - release-notes.md
